window.PEPCISION_PRODUCTS={
'mots-c':{name:'MOTS-c',size:'15 mg',slug:'mots-c',category:'Mitochondrial research',summary:'A defined peptide supplied for controlled laboratory research.',description:'MOTS-c is supplied as a lyophilized research compound for qualified laboratory applications. Product information is provided for identification and research context only.',purity:'To be confirmed',storage:'Per lot documentation'},
'ipamorelin':{name:'Ipamorelin',size:'10 mg',slug:'ipamorelin',category:'Peptide research',summary:'A defined peptide supplied for controlled laboratory research.',description:'Ipamorelin is supplied as a lyophilized research compound for qualified laboratory applications. Product information is provided for identification and research context only.',purity:'To be confirmed',storage:'Per lot documentation'},
'tesamorelin':{name:'Tesamorelin',size:'10 mg',slug:'tesamorelin',category:'Peptide research',summary:'A defined peptide supplied for controlled laboratory research.',description:'Tesamorelin is supplied as a lyophilized research compound for qualified laboratory applications. Product information is provided for identification and research context only.',purity:'To be confirmed',storage:'Per lot documentation'},
'aod9604':{name:'AOD9604',size:'5 mg',slug:'aod9604',category:'Peptide research',summary:'A defined peptide supplied for controlled laboratory research.',description:'AOD9604 is supplied as a lyophilized research compound for qualified laboratory applications. Product information is provided for identification and research context only.',purity:'To be confirmed',storage:'Per lot documentation'},
'bpc157':{name:'BPC-157',size:'5 mg',slug:'bpc157',category:'Peptide research',summary:'A defined peptide supplied for controlled laboratory research.',description:'BPC-157 is supplied as a lyophilized research compound for qualified laboratory applications. Product information is provided for identification and research context only.',purity:'To be confirmed',storage:'Per lot documentation'},
'ghk-cu':{name:'GHK-Cu',size:'Confirm size',slug:'ghk-cu',category:'Copper peptide research',summary:'A defined peptide supplied for controlled laboratory research.',description:'GHK-Cu is supplied as a research compound for qualified laboratory applications. Product information is provided for identification and research context only.',purity:'To be confirmed',storage:'Per lot documentation'},
'retatrutide':{name:'Retatrutide',size:'10 mg',slug:'retatrutide',category:'Peptide research',summary:'A defined peptide supplied for controlled laboratory research.',description:'Retatrutide is supplied only for qualified laboratory research. No human-use, dosing, treatment, or outcome claims are made on this site.',purity:'To be confirmed',storage:'Per lot documentation'}
};
