// Generated by scripts/build-chat-demo.mjs. Edit the approved source files instead.
(() => {
// Versioned, manually curated text from the existing site. Changes require code review.
// Never ingest arbitrary web pages, uploaded documents, or user-provided URLs here.
const POLICY_VERSION = '2026-09-26.1';
const REFUSAL = 'I can’t provide guidance on human or animal use, dosage, injection, reconstitution, treatment, side effects, or health outcomes. Pepcision products are for laboratory research use only and are not for human or animal consumption. I can help with documentation, shipping, availability, or order support.';
const HANDOFF = 'I don’t have approved information to answer that. Contact the Pepcision team at orders@pepcision.com for product documentation, availability, or order support. Please do not include payment details or medical information.';
const SENSITIVE = 'Please don’t share personal, payment, account, or medical information in chat. For order support, contact orders@pepcision.com. I can help with general documentation and shipping questions.';
const KB = Object.freeze([
  { id: 'shipping', title: 'Shipping & fulfillment', answer: 'Orders are fulfilled from Tampa, Florida. Pepcision does not direct-ship customer orders from overseas. For delivery timing, destinations, or shipping charges, contact orders@pepcision.com.', source: '/faq.html', sourceLabel: 'Shipping FAQ', phrases: ['shipping', 'where do orders ship from', 'where do you ship from', 'shipping and fulfillment'] },
  { id: 'coa', title: 'COAs & lot documents', answer: 'Lot-specific analytical documentation is provided when available. Contact orders@pepcision.com with the product and lot number you need. I can’t confirm a lot’s purity or testing results without its documentation.', source: '/faq.html', sourceLabel: 'Documentation FAQ', phrases: ['coa', 'coas', 'do you provide coas', 'lot documents', 'documentation', 'purity'] },
  { id: 'availability', title: 'Product availability', answer: 'Contact orders@pepcision.com for current product availability. This chat does not have live inventory or pricing.', source: '/contact.html', sourceLabel: 'Contact Pepcision', phrases: ['availability', 'product availability', 'what is in stock', 'pricing'] },
  { id: 'storage', title: 'Storage documentation', answer: 'Refer to the documentation for your specific product and lot for storage information. Contact orders@pepcision.com if you need those documents. I don’t have approved temperatures, shelf lives, or preparation instructions to provide.', source: '/contact.html', sourceLabel: 'Request lot documentation', phrases: ['storage', 'storage documentation', 'how should products be stored'] },
  { id: 'support', title: 'Order support', answer: 'For order questions, contact orders@pepcision.com. This chat cannot access order records or process payments. Do not share card details, passwords, or medical information here.', source: '/contact.html', sourceLabel: 'Contact Pepcision', phrases: ['support', 'order support', 'contact', 'contact support', 'where is my order', 'payment'] },
  { id: 'research_policy', title: 'Research-use policy', answer: 'Pepcision products are for laboratory research use only and are not for human or animal consumption. Pepcision does not provide medical, dosing, reconstitution, or human-use guidance.', source: '/faq.html', sourceLabel: 'Research-use FAQ', phrases: ['research use policy', 'research only', 'what is your research use policy'] }
].map(entry => Object.freeze({ ...entry, active: true, reviewedAt: '2026-09-26', expiresAt: '2026-12-25', provenance: 'Existing Pepcision site; curated for this implementation' })));

function approvedEntry(id, now = new Date()) {
  return KB.find(entry => entry.id === id && entry.active && now < new Date(`${entry.expiresAt}T23:59:59Z`));
}

// The server always builds the response; model-generated text never crosses this boundary.
function renderDecision(decision, now = new Date()) {
  if (decision.action === 'refused') return { action: 'refused', answer: REFUSAL, source: null };
  if (decision.action === 'sensitive') return { action: 'sensitive', answer: SENSITIVE, source: null };
  const entry = decision.action === 'answered' && approvedEntry(decision.answerId, now);
  if (!entry) return { action: 'escalated', answer: HANDOFF, source: null };
  return { action: 'answered', answer: entry.answer, source: { path: entry.source, label: entry.sourceLabel } };
}


function normalize(message) {
  return message.normalize('NFKC').replace(/[\u200B-\u200F\u202A-\u202E\u2060-\u206F\uFEFF]/g, '').toLowerCase().replace(/[’‘]/g, "'");
}

const blocked = [
  ['dosing', /\b(dos(?:e|es|ing|age)|microdos\w*|inject\w*|syringe\w*|reconstitut\w*|stack(?:ing)?|protocol\w*|bacteriostatic|subcutaneous|intramuscular)\b/],
  ['medical_advice', /\b(medic\w*|treat\w*|cure\w*|disease\w*|diagnos\w*|symptom\w*|side effects?|safe(?:ty)?|pain|diabet\w*|cancer|pregnan\w*|breastfeed\w*|heal\w*|injur\w*|weight\s*loss|lose\s*weight|fat\s*loss|muscle|bodybuild\w*|therap\w*|benefits?|blood|overdose)\b/],
  ['human_use', /\b(human|animal|consum\w*|ingest\w*|swallow\w*|drink|eat|take|taking|use on|use in|my body|my dog|my cat|for me|for my|patient\w*|pet|vet|skin|oral|topical|daily|weekly|how much|how often|mix|dilut\w*)\b/],
  ['unsafe', /\b(ignore|override|bypass|jailbreak|system prompt|developer message|roleplay|pretend|encode|decode|base64|translate|hypothetical|fictional|instructions above|previous instructions)\b/]
];

function redact(message) {
  return message
    .replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[EMAIL]')
    .replace(/(?:\+?\d[\d ().-]{6,}\d)/g, '[NUMBER]')
    .replace(/\b(?:sk-|pat|ghp_)[A-Za-z0-9_-]{10,}\b/g, '[SECRET]')
    .replace(/https?:\/\/\S+/gi, '[URL]');
}

function localDecision(message) {
  const text = normalize(message);
  const compact = text.replace(/[\s._-]/g, '').replace(/0/g, 'o').replace(/3/g, 'e').replace(/4/g, 'a');
  for (const [intent, regex] of blocked) {
    if (regex.test(text)) return { action: 'refused', intent, trigger: 'local_policy', answerId: 'none', classifier: 'local' };
  }
  if (/dosage|dosing|inject|reconstitut|humanconsumption/.test(compact)) return { action: 'refused', intent: 'dosing', trigger: 'obfuscated_policy', answerId: 'none', classifier: 'local' };
  if (redact(message) !== message || /\b(my name is|my address|password|card number|social security|order #)\b/i.test(text)) {
    return { action: 'sensitive', intent: 'sensitive', trigger: 'personal_data', answerId: 'none', classifier: 'local' };
  }
  const exact = text.trim().replace(/[?!.,]+$/, '').replace(/&/g, 'and').replace(/-/g, ' ').replace(/\s+/g, ' ');
  const entry = KB.find(item => item.phrases.includes(exact));
  if (entry) return { action: 'answered', intent: entry.id, trigger: 'approved_phrase', answerId: entry.id, classifier: 'local' };
  return null;
}


window.PepcisionChatDemo = Object.freeze({ reply(message) {
  if (typeof message !== 'string' || !message.trim() || message.length > 1000) throw new Error('Enter a message of 1–1,000 characters.');
  const decision = localDecision(message);
  if (!decision && /^(hi|hello|hey|thanks|thank you)[!.?]*$/i.test(message.trim())) return { answer: 'Hello! This is the Pepcision demo. Try Shipping, Availability, Order support, or a documentation question. Replies are preset; there is no live AI or order access.', source: null };
  return renderDecision(decision || { action: 'escalated' });
} });
})();
