// Generated by scripts/build-chat-demo.mjs. Edit the approved source files instead.
(() => {
function runPepcisionAgeGate() {
  const script = document.currentScript;
  const base = new URL('.', script?.src || location.href);
  const config = {
    brandName: 'Pepcision',
    minAge: 18,
    storageKey: 'pepcision_age_gate_v2',
    expirationDays: 30,
    leaveUrl: 'https://www.google.com/',
    logoUrl: new URL('../assets/pepcision-logo.png', base).href
  };

  if (document.getElementById('pepcision-age-gate')) return;

  try {
    const saved = JSON.parse(localStorage.getItem(config.storageKey) || 'null');
    const expiresAt = saved?.acceptedAt + config.expirationDays * 24 * 60 * 60 * 1000;
    if (saved?.accepted && Date.now() < expiresAt) return;
  } catch (error) {
    localStorage.removeItem(config.storageKey);
  }

  const previousOverflow = document.documentElement.style.overflow;
  document.documentElement.style.overflow = 'hidden';

  const gate = document.createElement('div');
  gate.id = 'pepcision-age-gate';
  gate.innerHTML = `
    <style>
      #pepcision-age-gate{
        position:fixed;
        inset:0;
        z-index:999999;
        display:flex;
        align-items:center;
        justify-content:center;
        min-height:100vh;
        min-height:100svh;
        padding:22px;
        background:linear-gradient(110deg,#f3f8fb,#fff 58%);
        font-family:"Source Sans 3","Trebuchet MS",Arial,sans-serif;
        color:#10223d;
      }
      #pepcision-age-gate *{box-sizing:border-box}
      .pepcision-gate-card{
        width:min(100%,540px);
        padding:36px;
        border:1px solid #dce7ee;
        border-radius:24px;
        background:#fff;
        box-shadow:0 18px 50px rgba(16,34,61,.16);
        text-align:center;
      }
      .pepcision-logo{
        max-width:190px;
        max-height:78px;
        object-fit:contain;
        margin:0 auto 18px;
        display:block;
      }
      .pepcision-badge{
        display:inline-flex;
        align-items:center;
        justify-content:center;
        margin-bottom:18px;
        padding:6px 12px;
        border-radius:999px;
        background:#e9f4fb;
        border:1px solid #dce7ee;
        color:#1766ad;
        font-size:13px;
        font-weight:800;
        text-transform:uppercase;
        letter-spacing:.08em;
      }
      .pepcision-brand{
        margin:0 0 10px;
        font-family:Barlow,"Arial Narrow",Arial,sans-serif;
        font-size:clamp(28px,7vw,34px);
        font-weight:800;
        line-height:1.05;
        letter-spacing:-.025em;
        color:#10223d;
      }
      .pepcision-copy{
        margin:0 0 22px;
        color:#627487;
        font-size:16px;
        line-height:1.55;
      }
      .pepcision-confirm{
        display:grid;
        grid-template-columns:20px 1fr;
        gap:12px;
        align-items:start;
        width:100%;
        margin:22px 0;
        padding:14px;
        border-radius:14px;
        background:#f3f8fb;
        border:1px solid #dce7ee;
        color:#10223d;
        font-size:15px;
        line-height:1.42;
        text-align:left;
      }
      #pepcision-age-gate .pepcision-confirm input[type="checkbox"]{
        width:18px;
        min-width:18px;
        height:18px;
        margin:2px 0 0;
        padding:0;
        accent-color:#2579c7;
        justify-self:start;
      }
      .pepcision-actions{
        display:grid;
        grid-template-columns:1fr 1fr;
        gap:12px;
      }
      .pepcision-btn{
        border:0;
        border-radius:999px;
        min-height:48px;
        padding:13px 20px;
        cursor:pointer;
        font-weight:800;
        font-size:16px;
        line-height:1.2;
      }
      .pepcision-enter{background:#2579c7;color:#fff}
      .pepcision-enter:not(:disabled):hover{background:#1766ad}
      .pepcision-enter:disabled{opacity:.45;cursor:not-allowed}
      .pepcision-leave{background:#fff;color:#10223d;border:1px solid #a9bfce}
      .pepcision-small{margin-top:18px;color:#627487;font-size:12px;line-height:1.5}
      @media(max-width:540px){
        #pepcision-age-gate{align-items:flex-start;padding:16px;padding-top:max(18px,env(safe-area-inset-top));overflow:auto}
        .pepcision-gate-card{padding:24px 18px;border-radius:20px}
        .pepcision-logo{max-width:165px;margin-bottom:14px}
        .pepcision-copy{font-size:15px}
        .pepcision-confirm{grid-template-columns:18px minmax(0,1fr);gap:10px;padding:13px;font-size:14px}
        .pepcision-actions{grid-template-columns:1fr}
      }
    </style>
    <div class="pepcision-gate-card" role="dialog" aria-modal="true" aria-labelledby="pepcision-gate-title">
      <img class="pepcision-logo" src="${config.logoUrl}" alt="${config.brandName} logo">
      <div class="pepcision-badge">${config.minAge}+ Access Required</div>
      <h1 class="pepcision-brand" id="pepcision-gate-title">Welcome to ${config.brandName}</h1>
      <p class="pepcision-copy">This website is intended for adults ${config.minAge} years of age or older. Products are offered for laboratory research purposes only and are not intended for human consumption, medical use, diagnosis, treatment, or prevention of disease.</p>
      <label class="pepcision-confirm"><input id="pepcision-age-checkbox" type="checkbox"><span>I confirm that I am at least ${config.minAge} years old and understand these products are for research use only.</span></label>
      <div class="pepcision-actions"><button id="pepcision-enter-site" class="pepcision-btn pepcision-enter" disabled>Enter Site</button><button id="pepcision-leave-site" class="pepcision-btn pepcision-leave">Leave Site</button></div>
      <div class="pepcision-small">By entering, you acknowledge and accept the site terms and research-use disclaimer.</div>
    </div>`;

  document.body.append(gate);
  const checkbox = gate.querySelector('#pepcision-age-checkbox');
  const enter = gate.querySelector('#pepcision-enter-site');
  const leave = gate.querySelector('#pepcision-leave-site');
  checkbox.addEventListener('change', () => { enter.disabled = !checkbox.checked; });
  enter.addEventListener('click', () => {
    localStorage.setItem(config.storageKey, JSON.stringify({ accepted: true, acceptedAt: Date.now() }));
    localStorage.setItem('pepcision_age_gate_v1', JSON.stringify({ accepted: true, acceptedAt: Date.now() }));
    gate.remove();
    document.documentElement.style.overflow = previousOverflow;
  });
  leave.addEventListener('click', () => { window.location.href = config.leaveUrl; });
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', runPepcisionAgeGate, { once: true }); else runPepcisionAgeGate();
// Versioned, manually curated text from the existing site. Changes require code review.
// Never ingest arbitrary web pages, uploaded documents, or user-provided URLs here.
const POLICY_VERSION = '2026-09-26.1';
const REFUSAL = 'I can’t provide guidance on human or animal use, dosage, injection, reconstitution, treatment, side effects, or health outcomes. Pepcision products are for laboratory research use only and are not for human or animal consumption. I can help with documentation, shipping, availability, or order support.';
const HANDOFF = 'I don’t have approved information to answer that. Contact the Pepcision team at orders@pepcision.com for product documentation, availability, or order support. Please do not include payment details or medical information.';
const SENSITIVE = 'Please don’t share personal, payment, account, or medical information in chat. For order support, contact orders@pepcision.com. I can help with general documentation and shipping questions.';
const KB = Object.freeze([
  { id: 'shipping', title: 'Shipping & fulfillment', answer: 'Orders are fulfilled from Tampa, Florida. Pepcision does not direct-ship customer orders from overseas. For delivery timing, destinations, or shipping charges, contact orders@pepcision.com.', source: '/faq.html', sourceLabel: 'Shipping FAQ', phrases: ['shipping', 'where do orders ship from', 'where do you ship from', 'shipping and fulfillment'] },
  { id: 'coa', title: 'COAs & lot documents', answer: 'Lot-specific analytical documentation is provided when available. Contact orders@pepcision.com with the product and lot number you need. I can’t confirm a lot’s purity or testing results without its documentation.', source: '/faq.html', sourceLabel: 'Documentation FAQ', phrases: ['coa', 'coas', 'do you provide coas', 'lot documents', 'documentation', 'purity'] },
  { id: 'availability', title: 'Product availability', answer: 'Contact orders@pepcision.com for current product availability. This chat does not have live inventory or pricing.', source: '/contact.html', sourceLabel: 'Contact Pepcision', phrases: ['availability', 'product availability', 'what is in stock', 'pricing'] },
  { id: 'storage', title: 'Storage documentation', answer: 'Refer to the documentation for your specific product and lot for storage information. Contact orders@pepcision.com if you need those documents. I don’t have approved temperatures, shelf lives, or preparation instructions to provide.', source: '/contact.html', sourceLabel: 'Request lot documentation', phrases: ['storage', 'storage documentation', 'how should products be stored'] },
  { id: 'support', title: 'Order support', answer: 'For order questions, contact orders@pepcision.com. This chat cannot access order records or process payments. Do not share card details, passwords, or medical information here.', source: '/contact.html', sourceLabel: 'Contact Pepcision', phrases: ['support', 'order support', 'contact', 'contact support', 'where is my order', 'payment'] },
  { id: 'research_policy', title: 'Research-use policy', answer: 'Pepcision products are for laboratory research use only and are not for human or animal consumption. Pepcision does not provide medical, dosing, reconstitution, or human-use guidance.', source: '/faq.html', sourceLabel: 'Research-use FAQ', phrases: ['research use policy', 'research only', 'what is your research use policy'] }
].map(entry => Object.freeze({ ...entry, active: true, reviewedAt: '2026-09-26', expiresAt: '2026-12-25', provenance: 'Existing Pepcision site; curated for this implementation' })));

function approvedEntry(id, now = new Date()) {
  return KB.find(entry => entry.id === id && entry.active && now < new Date(`${entry.expiresAt}T23:59:59Z`));
}

// The server always builds the response; model-generated text never crosses this boundary.
function renderDecision(decision, now = new Date()) {
  if (decision.action === 'refused') return { action: 'refused', answer: REFUSAL, source: null };
  if (decision.action === 'sensitive') return { action: 'sensitive', answer: SENSITIVE, source: null };
  const entry = decision.action === 'answered' && approvedEntry(decision.answerId, now);
  if (!entry) return { action: 'escalated', answer: HANDOFF, source: null };
  return { action: 'answered', answer: entry.answer, source: { path: entry.source, label: entry.sourceLabel } };
}


function normalize(message) {
  return message.normalize('NFKC').replace(/[\u200B-\u200F\u202A-\u202E\u2060-\u206F\uFEFF]/g, '').toLowerCase().replace(/[’‘]/g, "'");
}

const blocked = [
  ['dosing', /\b(dos(?:e|es|ing|age)|microdos\w*|inject\w*|syringe\w*|reconstitut\w*|stack(?:ing)?|protocol\w*|bacteriostatic|subcutaneous|intramuscular)\b/],
  ['medical_advice', /\b(medic\w*|treat\w*|cure\w*|disease\w*|diagnos\w*|symptom\w*|side effects?|safe(?:ty)?|pain|diabet\w*|cancer|pregnan\w*|breastfeed\w*|heal\w*|injur\w*|weight\s*loss|lose\s*weight|fat\s*loss|muscle|bodybuild\w*|therap\w*|benefits?|blood|overdose)\b/],
  ['human_use', /\b(human|animal|consum\w*|ingest\w*|swallow\w*|drink|eat|take|taking|use on|use in|my body|my dog|my cat|for me|for my|patient\w*|pet|vet|skin|oral|topical|daily|weekly|how much|how often|mix|dilut\w*)\b/],
  ['unsafe', /\b(ignore|override|bypass|jailbreak|system prompt|developer message|roleplay|pretend|encode|decode|base64|translate|hypothetical|fictional|instructions above|previous instructions)\b/]
];

function redact(message) {
  return message
    .replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, '[EMAIL]')
    .replace(/(?:\+?\d[\d ().-]{6,}\d)/g, '[NUMBER]')
    .replace(/\b(?:sk-|pat|ghp_)[A-Za-z0-9_-]{10,}\b/g, '[SECRET]')
    .replace(/https?:\/\/\S+/gi, '[URL]');
}

function localDecision(message) {
  const text = normalize(message);
  const compact = text.replace(/[\s._-]/g, '').replace(/0/g, 'o').replace(/3/g, 'e').replace(/4/g, 'a');
  for (const [intent, regex] of blocked) {
    if (regex.test(text)) return { action: 'refused', intent, trigger: 'local_policy', answerId: 'none', classifier: 'local' };
  }
  if (/dosage|dosing|inject|reconstitut|humanconsumption/.test(compact)) return { action: 'refused', intent: 'dosing', trigger: 'obfuscated_policy', answerId: 'none', classifier: 'local' };
  if (redact(message) !== message || /\b(my name is|my address|password|card number|social security|order #)\b/i.test(text)) {
    return { action: 'sensitive', intent: 'sensitive', trigger: 'personal_data', answerId: 'none', classifier: 'local' };
  }
  const exact = text.trim().replace(/[?!.,]+$/, '').replace(/&/g, 'and').replace(/-/g, ' ').replace(/\s+/g, ' ');
  const entry = KB.find(item => item.phrases.includes(exact));
  if (entry) return { action: 'answered', intent: entry.id, trigger: 'approved_phrase', answerId: entry.id, classifier: 'local' };
  return null;
}


window.PepcisionChatDemo = Object.freeze({ reply(message) {
  if (typeof message !== 'string' || !message.trim() || message.length > 1000) throw new Error('Enter a message of 1–1,000 characters.');
  const decision = localDecision(message);
  if (!decision && /^(hi|hello|hey|thanks|thank you)[!.?]*$/i.test(message.trim())) return { answer: 'Hello! This is the Pepcision demo. Try Shipping, Availability, Order support, or a documentation question. Replies are preset; there is no live AI or order access.', source: null };
  return renderDecision(decision || { action: 'escalated' });
} });
})();
